services:
  server:
    build: .
    environment:
      DATABASE_URL: "sqlite:///data/server.sqlite"
      OTEL_SERVICE_NAME: "server"
      OTEL_EXPORTER_OTLP_ENDPOINT: http://telemetry:4317
      TRACE_SAMPLE_PROBABILITY: 1.0
    ports:
      - "8001:8000"
    volumes:
      - ./data:/data

  telemetry:
    image: grafana/otel-lgtm:0.8.5
    healthcheck:
      test: ["CMD", "cat", "/tmp/ready"]
      timeout: 30s
      retries: 10
    environment:
      ENABLE_LOGS_OTELCOL: 'true'
      GF_AUTH_ANONYMOUS_ORG_NAME: 'Main Org.'
      GF_AUTH_DISABLE_LOGIN_FORM: 'true'
      ENABLE_LOGS_PROMETHEUS: 'true'
    ports:
      - "4317:4317"
      - "4318:4318"
      - "3000:3000"
    volumes:
      # Required for docker stats
      - /var/run/docker.sock:/var/run/docker.sock
