//! Build script for the database crate.

// generated by `sqlx migrate build-script`
fn main() {
    // trigger recompilation when a new migration is added
    println!("cargo:rerun-if-changed=migrations");
    // trigger recompilation if anything in .sqlx has changed, e.g. if we run prepare.
    println!("cargo:rerun-if-changed=../../.sqlx");
}
